### ISSUE TITLE
Open-Source Markdown Shell Extensions and Editor (Windows) and Viewer

### ISSUE THREAD

**Issue by carloBarazzetta** [mundimark/awesome-markdown-editors#44]
Please add those projects:

https://github.com/EtheaDev/MarkdownShellExtensions

https://github.com/EtheaDev/MarkdownHelpViewer

thanks

**Comment by geraldb** [comment]
@carloBarazzetta   Please add those projects:
thanks  - fyi: it's do-it-yourself.
